name       : python-pytest-timeout
version    : 1.4.2
release    : 1
source     :
    - https://github.com/pytest-dev/pytest-timeout/archive/1.4.2.tar.gz : d1015f696530fafe52cf8992e7c3d9e0968560150214d258bd5e7aa90b78c7c1
homepage   : https://github.com/pytest-dev/pytest-timeout/
license    : MIT
component  : programming.python
summary    : py.test plugin to abort hanging tests
description: |
    This is a plugin which will terminate tests after a certain timeout, assuming the test session isn't being debugged. When aborting a test it will show a stack dump of all threads running at the time. This is useful when running tests under a continuous integration server or simply if you don't know why the test suite hangs.
builddeps  :
    - python-pexpect
    - python-pytest-cov
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
