name       : python-pytest-timeout
version    : 2.1.0
release    : 5
source     :
    - https://github.com/pytest-dev/pytest-timeout/archive/refs/tags/2.1.0.tar.gz : e0087704c71081c37a918d4d8bb94c03875d46afdde1eef96b19a7f97b519abb
homepage   : https://github.com/pytest-dev/pytest-timeout/
license    : MIT
component  : programming.python
summary    : py.test plugin to abort hanging tests
description: |
    This is a plugin which will terminate tests after a certain timeout, assuming the test session isn't being debugged. When aborting a test it will show a stack dump of all threads running at the time. This is useful when running tests under a continuous integration server or simply if you don't know why the test suite hangs.
builddeps  :
    - python-pexpect
    - python-pytest-cov
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
